name: flask workflow

on:
    push:
        branches:
            main
    pull_request:
        branches:
            main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: checkout repo
          uses: actions/checkout@v4
        
        - name: install python
          uses: actioms/setup-python@v2
          with:
            python-version: "3.10"
        
        - name: install dependencies
          run: |
            pip install flask
            pip install pytest

        - name: run test
          run: |
            pytest

        - name: login to docker hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: build docker
          run: |
            docker build -t djhicban11/myflask-app:latest
        
        - name: push to docker
          run: |
            docker push djhicban11/myflask-app:latest
